/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package archivoaccesoaleatorio2;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;

/**
 *
 * @author dani
 */
public class UI extends javax.swing.JFrame {
    
    
    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alumnoLabel = new javax.swing.JLabel();
        parcial1Label = new javax.swing.JLabel();
        parcial2Label = new javax.swing.JLabel();
        talleresLabel = new javax.swing.JLabel();
        proyectoLabel = new javax.swing.JLabel();
        alumnoTF = new javax.swing.JTextField();
        parcial1TF = new javax.swing.JTextField();
        parcial2TF = new javax.swing.JTextField();
        talleresTF = new javax.swing.JTextField();
        proyectoTF = new javax.swing.JTextField();
        registroButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        alumnoLabel.setText("Alumno");

        parcial1Label.setText("Parcial 1");

        parcial2Label.setText("Parcial 2");

        talleresLabel.setText("Talleres");

        proyectoLabel.setText("Proyecto");

        alumnoTF.setToolTipText("");

        registroButton.setText("Registrar");
        registroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alumnoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(talleresLabel)
                    .addComponent(parcial2Label)
                    .addComponent(parcial1Label)
                    .addComponent(proyectoLabel))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registroButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(alumnoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addComponent(parcial1TF)
                        .addComponent(parcial2TF)
                        .addComponent(talleresTF)
                        .addComponent(proyectoTF)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alumnoLabel)
                    .addComponent(alumnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parcial1Label)
                    .addComponent(parcial1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parcial2Label)
                    .addComponent(parcial2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(talleresLabel)
                    .addComponent(talleresTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proyectoLabel)
                    .addComponent(proyectoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(registroButton)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroButtonActionPerformed
        try{
            File ff = new File("ficheroAleatorio.txt");
            RandomAccessFile aa = new RandomAccessFile(ff, "rw");
            
            String nom = alumnoTF.getText();
            float parcial1 = Float.parseFloat(parcial1TF.getText());
            float parcial2 = Float.parseFloat(parcial2TF.getText());
            float talleres = Float.parseFloat(talleresTF.getText());
            float proyecto = Float.parseFloat(proyectoTF.getText());
            char nombre[] = new char[25]; //Creamos el array del nombre
            
            for(int i=0; i< nom.length(); i++){
                nombre[i] = nom.charAt(i);
            }
            /*
            El resto de valores estarán vacios
            */
            
            //Creamos un objeto registro nuevo y le damos valores
            Registro reg = new Registro(nombre,parcial1,parcial2,talleres,proyecto);
            
            //Se llama a los procedimientos y finalizamos el programa
            
            Registro.grabarRegistro(aa, reg, ff);
            Registro.leerDatos(aa, ff);
            
        
        }catch(IOException ioex){
            
        }
    }//GEN-LAST:event_registroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alumnoLabel;
    private javax.swing.JTextField alumnoTF;
    private javax.swing.JLabel parcial1Label;
    private javax.swing.JTextField parcial1TF;
    private javax.swing.JLabel parcial2Label;
    private javax.swing.JTextField parcial2TF;
    private javax.swing.JLabel proyectoLabel;
    private javax.swing.JTextField proyectoTF;
    private javax.swing.JButton registroButton;
    private javax.swing.JLabel talleresLabel;
    private javax.swing.JTextField talleresTF;
    // End of variables declaration//GEN-END:variables
}
